# Generated by Django 4.2.16 on 2024-09-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
